# Generated by Django 5.0.6 on 2026-07-09 03:46

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('samples', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalReport',
            fields=[
                ('id', models.BigIntegerField(blank=True, db_index=True)),
                ('report_type', models.CharField(choices=[('failure_analysis_coa', 'Failure Analysis COA'), ('water_environmental_coa', 'Water/Environmental COA (DOH/DENR)'), ('training_cpd_certificate', 'Training CPD Certificate'), ('custom', 'Custom / Other')], max_length=32)),
                ('file_id', models.CharField(help_text='Alibaba Cloud OSS object key for the generated PDF.', max_length=512)),
                ('generated_at', models.DateTimeField(blank=True, editable=False)),
                ('version', models.PositiveIntegerField(default=1)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('generated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='samples.order')),
                ('sample', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='samples.sample')),
            ],
            options={
                'verbose_name': 'historical report',
                'verbose_name_plural': 'historical reports',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('failure_analysis_coa', 'Failure Analysis COA'), ('water_environmental_coa', 'Water/Environmental COA (DOH/DENR)'), ('training_cpd_certificate', 'Training CPD Certificate'), ('custom', 'Custom / Other')], max_length=32)),
                ('file_id', models.CharField(help_text='Alibaba Cloud OSS object key for the generated PDF.', max_length=512)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='samples.order')),
                ('sample', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='samples.sample')),
            ],
            options={
                'db_table': 'report',
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['report_type'], name='report_report__a84470_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.CheckConstraint(check=models.Q(('sample__isnull', False), ('order__isnull', False), _connector='OR'), name='report_target_required'),
        ),
    ]
