# Generated by Django 5.0.6 on 2026-08-19 02:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0001_initial"),
        ("samples", "0003_force_row_level_security"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalreport",
            name="failure_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="historicalreport",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("generating", "Generating"),
                    ("ready", "Ready"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="failure_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="report",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("generating", "Generating"),
                    ("ready", "Ready"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="historicalreport",
            name="file_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Alibaba Cloud OSS object key for the generated PDF. Set by the generation task.",
                max_length=512,
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="file_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Alibaba Cloud OSS object key for the generated PDF. Set by the generation task.",
                max_length=512,
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(fields=["status"], name="report_status_74972f_idx"),
        ),
    ]
