# Generated by Django 5.0.6 on 2026-08-27 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NotificationRecord",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("system_failure", "System failure recorded"),
                            ("open_failure_digest", "Daily open system-failure digest"),
                            ("calibration_due", "Instrument calibration due"),
                            ("investigation_opened", "Investigation opened"),
                            (
                                "result_out_of_spec",
                                "Test result flagged out of specification",
                            ),
                            ("report_ready", "Report ready to download"),
                            (
                                "training_session_rescheduled",
                                "Training session rescheduled",
                            ),
                            (
                                "customer_email_verification",
                                "Customer email verification",
                            ),
                            (
                                "customer_duplicate_registration",
                                "Duplicate registration attempt",
                            ),
                        ],
                        max_length=40,
                    ),
                ),
                ("recipient", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=255)),
                ("entity_type", models.CharField(blank=True, max_length=64)),
                ("entity_id", models.BigIntegerField(blank=True, null=True)),
                ("dedupe_key", models.CharField(max_length=255, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("failure_reason", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "notification_record",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["kind", "-created_at"],
                        name="notificatio_kind_f392a5_idx",
                    ),
                    models.Index(
                        fields=["status"], name="notificatio_status_3d1015_idx"
                    ),
                    models.Index(
                        fields=["entity_type", "entity_id"],
                        name="notificatio_entity__ca28ef_idx",
                    ),
                ],
            },
        ),
    ]
