# Generated by Django 5.0.6 on 2026-08-27 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationrecord",
            name="context",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="notificationrecord",
            name="kind",
            field=models.CharField(
                choices=[
                    ("system_failure", "System failure recorded"),
                    ("open_failure_digest", "Daily open system-failure digest"),
                    ("calibration_due", "Instrument calibration due"),
                    ("investigation_opened", "Investigation opened"),
                    ("result_out_of_spec", "Test result flagged out of specification"),
                    ("sample_progress", "Sample reached a milestone"),
                    ("sample_progress_digest", "Daily sample-progress digest"),
                    ("report_ready", "Report ready to download"),
                    ("training_session_rescheduled", "Training session rescheduled"),
                    ("customer_email_verification", "Customer email verification"),
                    (
                        "customer_duplicate_registration",
                        "Duplicate registration attempt",
                    ),
                ],
                max_length=40,
            ),
        ),
    ]
