# Generated by Django 5.0.6 on 2026-08-28 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_notificationrecord_context_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationrecord",
            name="attempts",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="notificationrecord",
            name="last_attempt_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="notificationrecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("sent", "Sent"),
                    ("failed", "Failed (will be retried)"),
                    ("abandoned", "Abandoned (will not be retried)"),
                ],
                default="pending",
                max_length=16,
            ),
        ),
        migrations.AddIndex(
            model_name="notificationrecord",
            index=models.Index(
                fields=["status", "last_attempt_at"],
                name="notificatio_status_4e97ae_idx",
            ),
        ),
    ]
