# Generated by Django 5.0.6 on 2026-07-09 03:46

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalStandardReagent',
            fields=[
                ('id', models.BigIntegerField(blank=True, db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('lot_number', models.CharField(max_length=100)),
                ('crm_traceability_reference', models.CharField(help_text='Certified Reference Material traceability reference, ISO/IEC 17025:2017 6.5.', max_length=255)),
                ('opened_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('retired', 'Retired')], default='active', max_length=16)),
                ('storage_location', models.CharField(blank=True, max_length=255)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical standard reagent',
                'verbose_name_plural': 'historical standard reagents',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('model', models.CharField(choices=[('fesem', 'FESEM'), ('sem', 'SEM'), ('edx', 'EDX'), ('afm', 'AFM'), ('ir_obirch', 'IR-OBIRCH'), ('tga', 'TGA'), ('xrf', 'XRF'), ('ebsd', 'EBSD'), ('thermal_emission_microscope', 'Thermal Emission Microscope'), ('dsc', 'DSC'), ('other', 'Other')], max_length=32)),
                ('calibration_due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('in_service', 'In Service'), ('out_of_calibration', 'Out of Calibration'), ('retired', 'Retired')], default='in_service', max_length=32)),
                ('custodian', models.ForeignKey(blank=True, help_text='Must hold the Instrument Custodian role (Blueprint Section 3.1 Role).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custodied_instruments', to=settings.AUTH_USER_MODEL)),
                ('parent_instrument', models.ForeignKey(blank=True, help_text='For child detector components, e.g. EDX attached to FESEM.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_instruments', to='equipment.instrument')),
            ],
            options={
                'db_table': 'instrument',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalInstrument',
            fields=[
                ('id', models.BigIntegerField(blank=True, db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('model', models.CharField(choices=[('fesem', 'FESEM'), ('sem', 'SEM'), ('edx', 'EDX'), ('afm', 'AFM'), ('ir_obirch', 'IR-OBIRCH'), ('tga', 'TGA'), ('xrf', 'XRF'), ('ebsd', 'EBSD'), ('thermal_emission_microscope', 'Thermal Emission Microscope'), ('dsc', 'DSC'), ('other', 'Other')], max_length=32)),
                ('calibration_due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('in_service', 'In Service'), ('out_of_calibration', 'Out of Calibration'), ('retired', 'Retired')], default='in_service', max_length=32)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('custodian', models.ForeignKey(blank=True, db_constraint=False, help_text='Must hold the Instrument Custodian role (Blueprint Section 3.1 Role).', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent_instrument', models.ForeignKey(blank=True, db_constraint=False, help_text='For child detector components, e.g. EDX attached to FESEM.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='equipment.instrument')),
            ],
            options={
                'verbose_name': 'historical instrument',
                'verbose_name_plural': 'historical instruments',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCalibrationRecord',
            fields=[
                ('id', models.BigIntegerField(blank=True, db_index=True)),
                ('performed_at', models.DateTimeField()),
                ('result', models.CharField(help_text='e.g. pass, fail, conditional', max_length=32)),
                ('next_due_date', models.DateField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('performed_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('instrument', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='equipment.instrument')),
            ],
            options={
                'verbose_name': 'historical calibration record',
                'verbose_name_plural': 'historical calibration records',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='CalibrationRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('performed_at', models.DateTimeField()),
                ('result', models.CharField(help_text='e.g. pass, fail, conditional', max_length=32)),
                ('next_due_date', models.DateField()),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='performed_calibrations', to=settings.AUTH_USER_MODEL)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calibration_records', to='equipment.instrument')),
            ],
            options={
                'db_table': 'calibration_record',
                'ordering': ['-performed_at'],
            },
        ),
        migrations.CreateModel(
            name='StandardReagent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('lot_number', models.CharField(max_length=100)),
                ('crm_traceability_reference', models.CharField(help_text='Certified Reference Material traceability reference, ISO/IEC 17025:2017 6.5.', max_length=255)),
                ('opened_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('retired', 'Retired')], default='active', max_length=16)),
                ('storage_location', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'standard_reagent',
                'ordering': ['name', 'lot_number'],
                'indexes': [models.Index(fields=['status', 'expiry_date'], name='standard_re_status_e21c58_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='instrument',
            index=models.Index(fields=['status', 'calibration_due_date'], name='instrument_status_702f87_idx'),
        ),
    ]
