# Generated by Django 5.0.6 on 2026-08-27 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0005_historicalsystemfailure_systemfailure"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalsystemfailure",
            name="component",
            field=models.CharField(
                choices=[
                    ("report_generation", "Report generation"),
                    ("retention_sweep", "Retention sweep"),
                    ("object_storage", "Object storage"),
                    ("database", "Database"),
                    ("task_broker", "Task broker"),
                    ("scheduled_task", "Scheduled task"),
                    ("api_request", "API request"),
                    ("email", "Email delivery"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="systemfailure",
            name="component",
            field=models.CharField(
                choices=[
                    ("report_generation", "Report generation"),
                    ("retention_sweep", "Retention sweep"),
                    ("object_storage", "Object storage"),
                    ("database", "Database"),
                    ("task_broker", "Task broker"),
                    ("scheduled_task", "Scheduled task"),
                    ("api_request", "API request"),
                    ("email", "Email delivery"),
                ],
                max_length=32,
            ),
        ),
    ]
