# Generated by Django 5.0.6 on 2026-09-04 14:14

import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_invoice_row_level_security"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InvoiceLine",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "description",
                    models.CharField(
                        help_text="What the customer sees. Snapshotted, so renaming an offering never rewrites an issued invoice.",
                        max_length=255,
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("unit_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="PHP", max_length=3)),
                (
                    "vat_treatment",
                    models.CharField(
                        choices=[
                            ("exclusive", "VAT-exclusive (net)"),
                            ("inclusive", "VAT-inclusive (gross)"),
                        ],
                        default="exclusive",
                        max_length=16,
                    ),
                ),
                (
                    "vat_rate_pct",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("12.00"), max_digits=5
                    ),
                ),
                (
                    "discount_pct",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "invoice_line",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalInvoiceLine",
            fields=[
                ("id", models.BigIntegerField(blank=True, db_index=True)),
                (
                    "description",
                    models.CharField(
                        help_text="What the customer sees. Snapshotted, so renaming an offering never rewrites an issued invoice.",
                        max_length=255,
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("unit_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="PHP", max_length=3)),
                (
                    "vat_treatment",
                    models.CharField(
                        choices=[
                            ("exclusive", "VAT-exclusive (net)"),
                            ("inclusive", "VAT-inclusive (gross)"),
                        ],
                        default="exclusive",
                        max_length=16,
                    ),
                ),
                (
                    "vat_rate_pct",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("12.00"), max_digits=5
                    ),
                ),
                (
                    "discount_pct",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="billing.invoice",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical invoice line",
                "verbose_name_plural": "historical invoice lines",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
