# Generated by Django 5.0.6 on 2026-09-04 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0003_invoiceline_historicalinvoiceline"),
        ("samples", "0004_historicalorderitem_orderitem_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalinvoiceline",
            name="order_item",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="The order line billed. Null for a line entered by hand on an invoice with no order behind it.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="samples.orderitem",
            ),
        ),
        migrations.AddField(
            model_name="invoiceline",
            name="invoice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lines",
                to="billing.invoice",
            ),
        ),
        migrations.AddField(
            model_name="invoiceline",
            name="order_item",
            field=models.ForeignKey(
                blank=True,
                help_text="The order line billed. Null for a line entered by hand on an invoice with no order behind it.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoice_lines",
                to="samples.orderitem",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoiceline",
            constraint=models.CheckConstraint(
                check=models.Q(("quantity__gt", 0)),
                name="invoice_line_quantity_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoiceline",
            constraint=models.CheckConstraint(
                check=models.Q(("unit_amount__gte", 0)),
                name="invoice_line_unit_amount_not_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoiceline",
            constraint=models.CheckConstraint(
                check=models.Q(("discount_pct__gte", 0), ("discount_pct__lte", 100)),
                name="invoice_line_discount_within_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoiceline",
            constraint=models.UniqueConstraint(
                condition=models.Q(("order_item__isnull", False)),
                fields=("order_item",),
                name="invoice_line_one_per_order_item",
            ),
        ),
    ]
