# Generated by Django 5.0.6 on 2026-09-04 15:58

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0005_invoice_line_row_level_security"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalinvoiceline",
            name="discount_pct",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Applied to the line before VAT is split out, so a discounted VAT-inclusive rate still reconciles.",
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name="historicalinvoiceline",
            name="unit_amount",
            field=models.DecimalField(
                decimal_places=2,
                help_text="The figure as it stood when this line was created. Whether it includes VAT is stated by vat_treatment.",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="invoiceline",
            name="discount_pct",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Applied to the line before VAT is split out, so a discounted VAT-inclusive rate still reconciles.",
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name="invoiceline",
            name="unit_amount",
            field=models.DecimalField(
                decimal_places=2,
                help_text="The figure as it stood when this line was created. Whether it includes VAT is stated by vat_treatment.",
                max_digits=10,
            ),
        ),
    ]
