# Generated by Django 5.0.6 on 2026-07-09 03:46

import django.db.models.deletion
import django_fsm
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingCourse',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('cpd_units', models.DecimalField(decimal_places=2, help_text="Per NASAT's CPD-accredited trainings.", max_digits=5)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('early_bird_discount_pct', models.DecimalField(decimal_places=2, default=20.0, max_digits=5)),
                ('student_discount_pct', models.DecimalField(decimal_places=2, default=20.0, max_digits=5)),
            ],
            options={
                'db_table': 'training_course',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid')], default='unpaid', max_length=16)),
                ('discount_applied', models.DecimalField(decimal_places=2, default=0, help_text='System-calculated: the single highest valid discount (early-bird vs student), never stacked.', max_digits=5)),
                ('discount_override', models.DecimalField(blank=True, decimal_places=2, help_text='Admin/Training Coordinator-set manual discount, e.g. negotiated corporate rate. Overrides discount_applied when set.', max_digits=5, null=True)),
                ('certificate_issued', models.BooleanField(default=False)),
                ('status', django_fsm.FSMField(choices=[('confirmed', 'Confirmed'), ('rescheduled', 'Rescheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='confirmed', max_length=16, protected=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='accounts.customeruser')),
            ],
            options={
                'db_table': 'enrollment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalCreditNote',
            fields=[
                ('id', models.BigIntegerField(blank=True, db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('available', 'Available'), ('applied', 'Applied'), ('expired', 'Expired')], default='available', max_length=16)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('applied_to_enrollment', models.ForeignKey(blank=True, db_constraint=False, help_text='Set once the customer redeems this credit against a new Enrollment.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='training.enrollment')),
                ('customer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.customeruser')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('source_enrollment', models.ForeignKey(blank=True, db_constraint=False, help_text='The rescheduled Enrollment that generated this credit.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='training.enrollment')),
            ],
            options={
                'verbose_name': 'historical credit note',
                'verbose_name_plural': 'historical credit notes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalTrainingCourse',
            fields=[
                ('id', models.BigIntegerField(blank=True, db_index=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('cpd_units', models.DecimalField(decimal_places=2, help_text="Per NASAT's CPD-accredited trainings.", max_digits=5)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('early_bird_discount_pct', models.DecimalField(decimal_places=2, default=20.0, max_digits=5)),
                ('student_discount_pct', models.DecimalField(decimal_places=2, default=20.0, max_digits=5)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical training course',
                'verbose_name_plural': 'historical training courses',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalTrainingSession',
            fields=[
                ('id', models.BigIntegerField(blank=True, db_index=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('capacity', models.PositiveIntegerField(help_text='Maximum enrollments accepted.')),
                ('min_capacity', models.PositiveIntegerField(help_text='Minimum confirmed enrollments required by cancellation_threshold_days before start_date, or the session auto-transitions to pending_reschedule (ISO/IEC 17025:2017 6.2.2).')),
                ('cancellation_threshold_days', models.PositiveIntegerField(help_text='Days before start_date at which the Celery beat min_capacity check runs.')),
                ('status', django_fsm.FSMField(choices=[('scheduled', 'Scheduled'), ('pending_reschedule', 'Pending Reschedule'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=32, protected=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('instructor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='training.trainingcourse')),
            ],
            options={
                'verbose_name': 'historical training session',
                'verbose_name_plural': 'historical training sessions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('capacity', models.PositiveIntegerField(help_text='Maximum enrollments accepted.')),
                ('min_capacity', models.PositiveIntegerField(help_text='Minimum confirmed enrollments required by cancellation_threshold_days before start_date, or the session auto-transitions to pending_reschedule (ISO/IEC 17025:2017 6.2.2).')),
                ('cancellation_threshold_days', models.PositiveIntegerField(help_text='Days before start_date at which the Celery beat min_capacity check runs.')),
                ('status', django_fsm.FSMField(choices=[('scheduled', 'Scheduled'), ('pending_reschedule', 'Pending Reschedule'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=32, protected=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='training.trainingcourse')),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructed_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'training_session',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalEnrollment',
            fields=[
                ('id', models.BigIntegerField(blank=True, db_index=True)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid')], default='unpaid', max_length=16)),
                ('discount_applied', models.DecimalField(decimal_places=2, default=0, help_text='System-calculated: the single highest valid discount (early-bird vs student), never stacked.', max_digits=5)),
                ('discount_override', models.DecimalField(blank=True, decimal_places=2, help_text='Admin/Training Coordinator-set manual discount, e.g. negotiated corporate rate. Overrides discount_applied when set.', max_digits=5, null=True)),
                ('certificate_issued', models.BooleanField(default=False)),
                ('status', django_fsm.FSMField(choices=[('confirmed', 'Confirmed'), ('rescheduled', 'Rescheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='confirmed', max_length=16, protected=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('customer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.customeruser')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='training.trainingsession')),
            ],
            options={
                'verbose_name': 'historical enrollment',
                'verbose_name_plural': 'historical enrollments',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='training.trainingsession'),
        ),
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('available', 'Available'), ('applied', 'Applied'), ('expired', 'Expired')], default='available', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='accounts.customeruser')),
                ('applied_to_enrollment', models.ForeignKey(blank=True, help_text='Set once the customer redeems this credit against a new Enrollment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_notes_applied', to='training.enrollment')),
                ('source_enrollment', models.ForeignKey(help_text='The rescheduled Enrollment that generated this credit.', on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes_issued', to='training.enrollment')),
            ],
            options={
                'db_table': 'credit_note',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='credit_note_status_d38ab6_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='trainingsession',
            index=models.Index(fields=['status', 'start_date'], name='training_se_status_e7324a_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['status'], name='enrollment_status_0e6820_idx'),
        ),
    ]
