# Generated by Django 5.0.6 on 2026-07-09 03:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('documents', '0001_initial'),
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffuser',
            name='instrument_certifications',
            field=models.ManyToManyField(blank=True, help_text='Supports FR-C3-02 competency enforcement: role membership alone is not sufficient.', related_name='certified_staff', to='testing.testmethod'),
        ),
        migrations.AddField(
            model_name='staffuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='school_id_document',
            field=models.ForeignKey(blank=True, help_text='For student discount eligibility per NASAT catalog.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_discount_customers', to='documents.document'),
        ),
        migrations.AddField(
            model_name='esignature',
            name='signer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signatures', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcustomeruser',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcustomeruser',
            name='school_id_document',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='For student discount eligibility per NASAT catalog.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='documents.document'),
        ),
        migrations.AddField(
            model_name='historicalstaffuser',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staffuser',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='staff_users', to='accounts.role'),
        ),
        migrations.AddIndex(
            model_name='esignature',
            index=models.Index(fields=['signed_entity_type', 'signed_entity_id'], name='e_signature_signed__90a422_idx'),
        ),
    ]
