# Generated by Django 5.0.6 on 2026-07-09 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_seed_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='mfa_secret',
            field=models.CharField(blank=True, help_text='Base32 TOTP secret (RFC 6238). Set by /auth/customer/mfa/enable, only activated (mfa_enabled=True) once confirmed with a real code.', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='historicalcustomeruser',
            name='mfa_secret',
            field=models.CharField(blank=True, help_text='Base32 TOTP secret (RFC 6238). Set by /auth/customer/mfa/enable, only activated (mfa_enabled=True) once confirmed with a real code.', max_length=64, null=True),
        ),
    ]
