# Generated by Django 5.0.6 on 2026-08-23 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_customeruser_mfa_secret_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customeruser",
            name="mfa_last_used_timestep",
            field=models.BigIntegerField(
                blank=True,
                help_text="The TOTP time step of the last accepted code, so it cannot be replayed. Without it a code observed over someone's shoulder, or captured anywhere in transit, stayed usable for the whole validity window.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="customeruser",
            name="pending_mfa_secret",
            field=models.CharField(
                blank=True,
                help_text="A new secret being enrolled, held here until it is confirmed. Re-enrolling used to overwrite mfa_secret directly while mfa_enabled stayed True, which locked the customer out of their own account the moment they opened the enrolment screen: their authenticator still held the old secret and the server no longer accepted it.",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalcustomeruser",
            name="mfa_last_used_timestep",
            field=models.BigIntegerField(
                blank=True,
                help_text="The TOTP time step of the last accepted code, so it cannot be replayed. Without it a code observed over someone's shoulder, or captured anywhere in transit, stayed usable for the whole validity window.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalcustomeruser",
            name="pending_mfa_secret",
            field=models.CharField(
                blank=True,
                help_text="A new secret being enrolled, held here until it is confirmed. Re-enrolling used to overwrite mfa_secret directly while mfa_enabled stayed True, which locked the customer out of their own account the moment they opened the enrolment screen: their authenticator still held the old secret and the server no longer accepted it.",
                max_length=64,
                null=True,
            ),
        ),
    ]
