import { useState } from "react";
import { Link } from "react-router-dom";
import { useReportDownloadUrl, useReports } from "../api/queries";
import { REPORT_STATUS_LABELS, REPORT_TYPE_LABELS } from "../api/types";
import type { Report, ReportStatus } from "../api/types";
import { describeApiError } from "../api/client";

const STATUS_OPTIONS = Object.keys(REPORT_STATUS_LABELS) as ReportStatus[];

const STATUS_TOKENS: Record<ReportStatus, { bg: string; fg: string }> = {
  pending: { bg: "--color-status-neutral-bg", fg: "--color-status-neutral" },
  generating: { bg: "--color-warning-bg", fg: "--color-warning" },
  ready: { bg: "--color-success-bg", fg: "--color-success" },
  failed: { bg: "--color-danger-bg", fg: "--color-danger" },
};

function ReportStatusBadge({ status }: { status: ReportStatus }) {
  const tokens = STATUS_TOKENS[status];
  return (
    <span className="badge" style={{ background: `var(${tokens.bg})`, color: `var(${tokens.fg})` }}>
      {REPORT_STATUS_LABELS[status]}
    </span>
  );
}

export function ReportsList() {
  const [status, setStatus] = useState<string>("");
  const { data, isLoading, isError } = useReports({ status: status || undefined });
  const download = useReportDownloadUrl();
  const [failedFor, setFailedFor] = useState<number | null>(null);

  /**
   * The presigned URL is fetched on click and opened immediately rather than
   * rendered as an href: it expires (15 min by default), so an href written
   * at render time is a link that quietly stops working while the page is
   * open.
   */
  function openReport(report: Report) {
    setFailedFor(null);
    download.mutate(report.id, {
      onSuccess: ({ url }) => window.open(url, "_blank", "noopener,noreferrer"),
      onError: () => setFailedFor(report.id),
    });
  }

  return (
    <div>
      <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: 20 }}>
        <div>
          <h1 style={{ fontSize: "1.4rem", margin: "0 0 4px" }}>Reports</h1>
          <p style={{ color: "var(--color-text-muted)", margin: 0, fontSize: "0.9rem" }}>
            Generated COAs and certificates (Blueprint Section 2.1a). Reports are generated from an
            approved sample.
          </p>
        </div>
        <select value={status} onChange={(e) => setStatus(e.target.value)} className="btn" style={{ cursor: "pointer" }}>
          <option value="">All statuses</option>
          {STATUS_OPTIONS.map((s) => (
            <option key={s} value={s}>
              {REPORT_STATUS_LABELS[s]}
            </option>
          ))}
        </select>
      </div>

      <div className="card" style={{ overflow: "hidden" }}>
        {isLoading && <div style={{ padding: 24 }}>Loading…</div>}
        {isError && <div style={{ padding: 24, color: "var(--color-danger)" }}>Couldn't load reports.</div>}
        {data && data.results.length === 0 && (
          <div style={{ padding: 24, color: "var(--color-text-muted)" }}>
            No reports match this filter. Generate one from an approved sample.
          </div>
        )}
        {data && data.results.length > 0 && (
          <table>
            <thead>
              <tr>
                <th>Sample</th>
                <th>Type</th>
                <th>Version</th>
                <th>Status</th>
                <th>Generated by</th>
                <th>Generated</th>
                <th />
              </tr>
            </thead>
            <tbody>
              {data.results.map((report) => (
                <tr key={report.id} style={{ cursor: "default" }}>
                  <td style={{ fontWeight: 600 }}>
                    {report.sample ? (
                      <Link to={`/samples/${report.sample}`}>{report.sample_code ?? `Sample #${report.sample}`}</Link>
                    ) : (
                      `Order #${report.order}`
                    )}
                  </td>
                  <td>{REPORT_TYPE_LABELS[report.report_type]}</td>
                  <td>v{report.version}</td>
                  <td>
                    <ReportStatusBadge status={report.status} />
                    {report.status === "failed" && report.failure_reason && (
                      <div
                        style={{ color: "var(--color-text-muted)", fontSize: "0.75rem", marginTop: 4, maxWidth: 320 }}
                        title={report.failure_reason}
                      >
                        {report.failure_reason.slice(0, 90)}
                        {report.failure_reason.length > 90 ? "…" : ""}
                      </div>
                    )}
                  </td>
                  <td>{report.generated_by_display_name}</td>
                  <td>{new Date(report.generated_at).toLocaleString()}</td>
                  <td style={{ textAlign: "right" }}>
                    <button
                      className="btn"
                      disabled={report.status !== "ready" || download.isPending}
                      title={
                        report.status === "ready"
                          ? undefined
                          : `Not available while the report is '${report.status}'.`
                      }
                      onClick={() => openReport(report)}
                    >
                      Download
                    </button>
                    {failedFor === report.id && (
                      <div style={{ color: "var(--color-danger)", fontSize: "0.75rem", marginTop: 4 }}>
                        {describeApiError(download.error)}
                      </div>
                    )}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </div>
      {data && (
        <div style={{ marginTop: 12, color: "var(--color-text-muted)", fontSize: "0.85rem" }}>
          {data.count} total
        </div>
      )}
    </div>
  );
}
