# Generated by Django 5.0.6 on 2026-09-04 05:44

import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("testing", "0002_historicaltestresult_analyte_testresult_analyte"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalServiceOffering",
            fields=[
                ("id", models.BigIntegerField(blank=True, db_index=True)),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Rate-card code, as it appears on a quotation (e.g. 'WQ-BOD5'). Unique.",
                        max_length=32,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "service_line",
                    models.CharField(
                        choices=[
                            (
                                "failure_analysis",
                                "Failure Analysis / Materials Characterization",
                            ),
                            ("water_environmental", "Water / Environmental Testing"),
                            ("training", "Training"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "turnaround_days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Standard turnaround quoted to the customer, in working days. Null where it depends on the sample.",
                        null=True,
                    ),
                ),
                (
                    "is_accredited",
                    models.BooleanField(
                        default=False,
                        help_text="Within NASAT's ISO/IEC 17025 scope of accreditation. Affects what a report may claim, so it is stated per offering rather than assumed.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Withdrawn offerings stay in the catalogue rather than being deleted: past orders reference them, and 'what did we stop selling' is itself a question.",
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical service offering",
                "verbose_name_plural": "historical service offerings",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="ServiceOffering",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "code",
                    models.CharField(
                        help_text="Rate-card code, as it appears on a quotation (e.g. 'WQ-BOD5'). Unique.",
                        max_length=32,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "service_line",
                    models.CharField(
                        choices=[
                            (
                                "failure_analysis",
                                "Failure Analysis / Materials Characterization",
                            ),
                            ("water_environmental", "Water / Environmental Testing"),
                            ("training", "Training"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "turnaround_days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Standard turnaround quoted to the customer, in working days. Null where it depends on the sample.",
                        null=True,
                    ),
                ),
                (
                    "is_accredited",
                    models.BooleanField(
                        default=False,
                        help_text="Within NASAT's ISO/IEC 17025 scope of accreditation. Affects what a report may claim, so it is stated per offering rather than assumed.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Withdrawn offerings stay in the catalogue rather than being deleted: past orders reference them, and 'what did we stop selling' is itself a question.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "test_methods",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The method(s) that fulfil this offering. More than one for a panel; none for an offering not yet mapped to its methods.",
                        related_name="offerings",
                        to="testing.testmethod",
                    ),
                ),
            ],
            options={
                "db_table": "service_offering",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="OfferingPrice",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The figure as published. Whether it includes VAT is stated by vat_treatment, not inferred.",
                        max_digits=10,
                    ),
                ),
                ("currency", models.CharField(default="PHP", max_length=3)),
                (
                    "vat_treatment",
                    models.CharField(
                        choices=[
                            ("exclusive", "VAT-exclusive (net)"),
                            ("inclusive", "VAT-inclusive (gross)"),
                        ],
                        default="exclusive",
                        max_length=16,
                    ),
                ),
                (
                    "vat_rate_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("12.00"),
                        help_text="Philippine VAT is 12%. Stored per price so a zero-rated or exempt service is a value here, not a special case in code.",
                        max_digits=5,
                    ),
                ),
                ("effective_from", models.DateField()),
                (
                    "effective_to",
                    models.DateField(
                        blank=True,
                        help_text="Inclusive last day this price applied. Null means it is the current price.",
                        null=True,
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        help_text="Why this price exists — '2026 rate card', say.",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "offering",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="catalogue.serviceoffering",
                    ),
                ),
            ],
            options={
                "db_table": "offering_price",
                "ordering": ["-effective_from", "-id"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalOfferingPrice",
            fields=[
                ("id", models.BigIntegerField(blank=True, db_index=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The figure as published. Whether it includes VAT is stated by vat_treatment, not inferred.",
                        max_digits=10,
                    ),
                ),
                ("currency", models.CharField(default="PHP", max_length=3)),
                (
                    "vat_treatment",
                    models.CharField(
                        choices=[
                            ("exclusive", "VAT-exclusive (net)"),
                            ("inclusive", "VAT-inclusive (gross)"),
                        ],
                        default="exclusive",
                        max_length=16,
                    ),
                ),
                (
                    "vat_rate_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("12.00"),
                        help_text="Philippine VAT is 12%. Stored per price so a zero-rated or exempt service is a value here, not a special case in code.",
                        max_digits=5,
                    ),
                ),
                ("effective_from", models.DateField()),
                (
                    "effective_to",
                    models.DateField(
                        blank=True,
                        help_text="Inclusive last day this price applied. Null means it is the current price.",
                        null=True,
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        help_text="Why this price exists — '2026 rate card', say.",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "offering",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="catalogue.serviceoffering",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical offering price",
                "verbose_name_plural": "historical offering prices",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddIndex(
            model_name="serviceoffering",
            index=models.Index(
                fields=["service_line", "is_active"],
                name="service_off_service_a5c2c2_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="serviceoffering",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("service_line__in", ["failure_analysis", "water_environmental"])
                ),
                name="service_offering_analytical_service_line",
            ),
        ),
        migrations.AddConstraint(
            model_name="offeringprice",
            constraint=models.UniqueConstraint(
                fields=("offering", "effective_from"),
                name="offering_price_one_per_start_date",
            ),
        ),
        migrations.AddConstraint(
            model_name="offeringprice",
            constraint=models.CheckConstraint(
                check=models.Q(("amount__gte", 0)),
                name="offering_price_amount_not_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="offeringprice",
            constraint=models.CheckConstraint(
                check=models.Q(("vat_rate_pct__gte", 0)),
                name="offering_price_vat_rate_not_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="offeringprice",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("effective_to__isnull", True),
                    ("effective_to__gte", models.F("effective_from")),
                    _connector="OR",
                ),
                name="offering_price_window_not_backwards",
            ),
        ),
    ]
