# Generated by Django 5.0.6 on 2026-09-04 15:58

import django.db.models.deletion
import django_fsm
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0005_customer_mfa_hardening"),
        ("catalogue", "0001_initial"),
        ("samples", "0006_alter_historicalorderitem_unit_amount_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Quotation",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "reference",
                    models.CharField(
                        editable=False,
                        help_text="What the customer quotes back at the lab on a purchase order (Q-2026-00042).",
                        max_length=32,
                        unique=True,
                    ),
                ),
                (
                    "service_line",
                    models.CharField(
                        choices=[
                            (
                                "failure_analysis",
                                "Failure Analysis / Materials Characterization",
                            ),
                            ("water_environmental", "Water / Environmental Testing"),
                            ("training", "Training"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    django_fsm.FSMField(
                        choices=[
                            ("draft", "Draft"),
                            ("sent", "Sent"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("expired", "Expired"),
                        ],
                        default="draft",
                        max_length=16,
                        protected=True,
                    ),
                ),
                (
                    "valid_until",
                    models.DateField(
                        help_text="Last day the customer can accept. A quote with no end is not a quote."
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Terms, scope caveats, anything the customer should read.",
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "accepted_by_customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="accounts.customeruser",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quotations",
                        to="accounts.customeruser",
                    ),
                ),
                (
                    "decided_by_staff",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set when the quotation is raised against an order that already exists; otherwise accepting creates one.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quotations",
                        to="samples.order",
                    ),
                ),
                (
                    "prepared_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prepared_quotations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supersedes",
                    models.ForeignKey(
                        blank=True,
                        help_text="The quotation this one replaces. Revising a sent quotation means issuing a new one, never editing it.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="superseded_by",
                        to="quotations.quotation",
                    ),
                ),
            ],
            options={
                "db_table": "quotation",
                "ordering": ["-created_at"],
            },
            bases=(django_fsm.FSMModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalQuotationItem",
            fields=[
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "unit_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The figure as it stood when this line was created. Whether it includes VAT is stated by vat_treatment.",
                        max_digits=10,
                    ),
                ),
                ("currency", models.CharField(default="PHP", max_length=3)),
                (
                    "vat_treatment",
                    models.CharField(
                        choices=[
                            ("exclusive", "VAT-exclusive (net)"),
                            ("inclusive", "VAT-inclusive (gross)"),
                        ],
                        default="exclusive",
                        max_length=16,
                    ),
                ),
                (
                    "vat_rate_pct",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("12.00"), max_digits=5
                    ),
                ),
                (
                    "discount_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Applied to the line before VAT is split out, so a discounted VAT-inclusive rate still reconciles.",
                        max_digits=5,
                    ),
                ),
                ("id", models.BigIntegerField(blank=True, db_index=True)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "offering",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="catalogue.serviceoffering",
                    ),
                ),
                (
                    "source_price",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="catalogue.offeringprice",
                    ),
                ),
                (
                    "quotation",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="quotations.quotation",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical quotation item",
                "verbose_name_plural": "historical quotation items",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalQuotation",
            fields=[
                ("id", models.BigIntegerField(blank=True, db_index=True)),
                (
                    "reference",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        help_text="What the customer quotes back at the lab on a purchase order (Q-2026-00042).",
                        max_length=32,
                    ),
                ),
                (
                    "service_line",
                    models.CharField(
                        choices=[
                            (
                                "failure_analysis",
                                "Failure Analysis / Materials Characterization",
                            ),
                            ("water_environmental", "Water / Environmental Testing"),
                            ("training", "Training"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    django_fsm.FSMField(
                        choices=[
                            ("draft", "Draft"),
                            ("sent", "Sent"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("expired", "Expired"),
                        ],
                        default="draft",
                        max_length=16,
                        protected=True,
                    ),
                ),
                (
                    "valid_until",
                    models.DateField(
                        help_text="Last day the customer can accept. A quote with no end is not a quote."
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Terms, scope caveats, anything the customer should read.",
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "accepted_by_customer",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="accounts.customeruser",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="accounts.customeruser",
                    ),
                ),
                (
                    "decided_by_staff",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Set when the quotation is raised against an order that already exists; otherwise accepting creates one.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="samples.order",
                    ),
                ),
                (
                    "prepared_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supersedes",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="The quotation this one replaces. Revising a sent quotation means issuing a new one, never editing it.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="quotations.quotation",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical quotation",
                "verbose_name_plural": "historical quotations",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="QuotationItem",
            fields=[
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "unit_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The figure as it stood when this line was created. Whether it includes VAT is stated by vat_treatment.",
                        max_digits=10,
                    ),
                ),
                ("currency", models.CharField(default="PHP", max_length=3)),
                (
                    "vat_treatment",
                    models.CharField(
                        choices=[
                            ("exclusive", "VAT-exclusive (net)"),
                            ("inclusive", "VAT-inclusive (gross)"),
                        ],
                        default="exclusive",
                        max_length=16,
                    ),
                ),
                (
                    "vat_rate_pct",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("12.00"), max_digits=5
                    ),
                ),
                (
                    "discount_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Applied to the line before VAT is split out, so a discounted VAT-inclusive rate still reconciles.",
                        max_digits=5,
                    ),
                ),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "offering",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quotation_items",
                        to="catalogue.serviceoffering",
                    ),
                ),
                (
                    "quotation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="quotations.quotation",
                    ),
                ),
                (
                    "source_price",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="catalogue.offeringprice",
                    ),
                ),
            ],
            options={
                "db_table": "quotation_item",
                "ordering": ["id"],
            },
        ),
        migrations.AddIndex(
            model_name="quotation",
            index=models.Index(
                fields=["status", "valid_until"], name="quotation_status_930e99_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="quotationitem",
            constraint=models.CheckConstraint(
                check=models.Q(("quantity__gt", 0)),
                name="quotation_item_quantity_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="quotationitem",
            constraint=models.CheckConstraint(
                check=models.Q(("unit_amount__gte", 0)),
                name="quotation_item_unit_amount_not_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="quotationitem",
            constraint=models.CheckConstraint(
                check=models.Q(("discount_pct__gte", 0), ("discount_pct__lte", 100)),
                name="quotation_item_discount_within_range",
            ),
        ),
    ]
