# Generated by Django 5.0.6 on 2026-07-09 03:46

import django.db.models.deletion
import django_fsm
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalOrder',
            fields=[
                ('id', models.BigIntegerField(blank=True, db_index=True)),
                ('service_line', models.CharField(choices=[('failure_analysis', 'Failure Analysis / Materials Characterization'), ('water_environmental', 'Water / Environmental Testing'), ('training', 'Training')], max_length=32)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=16)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('customer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.customeruser')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical order',
                'verbose_name_plural': 'historical orders',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('service_line', models.CharField(choices=[('failure_analysis', 'Failure Analysis / Materials Characterization'), ('water_environmental', 'Water / Environmental Testing'), ('training', 'Training')], max_length=32)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='accounts.customeruser')),
            ],
            options={
                'db_table': 'order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalSample',
            fields=[
                ('id', models.BigIntegerField(blank=True, db_index=True)),
                ('service_line', models.CharField(choices=[('failure_analysis', 'Failure Analysis / Materials Characterization'), ('water_environmental', 'Water / Environmental Testing'), ('training', 'Training')], max_length=32)),
                ('unique_sample_code', models.CharField(db_index=True, max_length=64)),
                ('client_reference', models.CharField(blank=True, max_length=128)),
                ('sampling_point', models.CharField(blank=True, max_length=255)),
                ('collection_datetime', models.DateTimeField(blank=True, null=True)),
                ('container_type', models.CharField(blank=True, max_length=128)),
                ('container_count', models.PositiveIntegerField(default=1)),
                ('preservation_method', models.CharField(blank=True, max_length=255)),
                ('retention_period', models.CharField(blank=True, help_text='Physical sample retention, distinct from RetentionPolicy record retention (Section 3.1a).', max_length=128)),
                ('holding_time', models.DurationField(blank=True, null=True)),
                ('status', django_fsm.FSMField(choices=[('pre_registered', 'Pre-registered'), ('registered', 'Registered'), ('received', 'Received'), ('in_prep', 'In Prep'), ('in_testing', 'In Testing'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('under_investigation', 'Under Investigation'), ('retest_pending', 'Retest Pending'), ('disposed', 'Disposed')], default='pre_registered', max_length=32, protected=True)),
                ('safety_flags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, db_constraint=False, help_text='Nullable for walk-in/non-portal samples.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='samples.order')),
            ],
            options={
                'verbose_name': 'historical sample',
                'verbose_name_plural': 'historical samples',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('service_line', models.CharField(choices=[('failure_analysis', 'Failure Analysis / Materials Characterization'), ('water_environmental', 'Water / Environmental Testing'), ('training', 'Training')], max_length=32)),
                ('unique_sample_code', models.CharField(db_index=True, max_length=64, unique=True)),
                ('client_reference', models.CharField(blank=True, max_length=128)),
                ('sampling_point', models.CharField(blank=True, max_length=255)),
                ('collection_datetime', models.DateTimeField(blank=True, null=True)),
                ('container_type', models.CharField(blank=True, max_length=128)),
                ('container_count', models.PositiveIntegerField(default=1)),
                ('preservation_method', models.CharField(blank=True, max_length=255)),
                ('retention_period', models.CharField(blank=True, help_text='Physical sample retention, distinct from RetentionPolicy record retention (Section 3.1a).', max_length=128)),
                ('holding_time', models.DurationField(blank=True, null=True)),
                ('status', django_fsm.FSMField(choices=[('pre_registered', 'Pre-registered'), ('registered', 'Registered'), ('received', 'Received'), ('in_prep', 'In Prep'), ('in_testing', 'In Testing'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('under_investigation', 'Under Investigation'), ('retest_pending', 'Retest Pending'), ('disposed', 'Disposed')], default='pre_registered', max_length=32, protected=True)),
                ('safety_flags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(blank=True, help_text='Nullable for walk-in/non-portal samples.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='samples', to='samples.order')),
            ],
            options={
                'db_table': 'sample',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalChainOfCustodyEvent',
            fields=[
                ('id', models.BigIntegerField(blank=True, db_index=True)),
                ('from_location', models.CharField(blank=True, max_length=255)),
                ('to_location', models.CharField(blank=True, max_length=255)),
                ('timestamp', models.DateTimeField(blank=True, editable=False)),
                ('event_type', models.CharField(choices=[('receipt', 'Receipt'), ('transfer', 'Transfer'), ('aliquot', 'Aliquot'), ('disposal', 'Disposal')], max_length=16)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('from_holder', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('to_holder', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sample', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='samples.sample')),
            ],
            options={
                'verbose_name': 'historical chain of custody event',
                'verbose_name_plural': 'historical chain of custody events',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ChainOfCustodyEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('from_location', models.CharField(blank=True, max_length=255)),
                ('to_location', models.CharField(blank=True, max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(choices=[('receipt', 'Receipt'), ('transfer', 'Transfer'), ('aliquot', 'Aliquot'), ('disposal', 'Disposal')], max_length=16)),
                ('from_holder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custody_events_released', to=settings.AUTH_USER_MODEL)),
                ('to_holder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custody_events_received', to=settings.AUTH_USER_MODEL)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chain_of_custody_events', to='samples.sample')),
            ],
            options={
                'db_table': 'chain_of_custody_event',
                'ordering': ['sample_id', 'timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='sample',
            index=models.Index(fields=['status', 'service_line'], name='sample_status_775d60_idx'),
        ),
    ]
