# Generated by Django 5.0.6 on 2026-09-04 14:14

import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0001_initial"),
        ("samples", "0003_force_row_level_security"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalOrderItem",
            fields=[
                ("id", models.BigIntegerField(blank=True, db_index=True)),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "unit_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The offering's published figure at the moment this line was created. Whether it includes VAT is stated by vat_treatment.",
                        max_digits=10,
                    ),
                ),
                ("currency", models.CharField(default="PHP", max_length=3)),
                (
                    "vat_treatment",
                    models.CharField(
                        choices=[
                            ("exclusive", "VAT-exclusive (net)"),
                            ("inclusive", "VAT-inclusive (gross)"),
                        ],
                        default="exclusive",
                        max_length=16,
                    ),
                ),
                (
                    "vat_rate_pct",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("12.00"), max_digits=5
                    ),
                ),
                (
                    "discount_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Applied to the line before VAT is split out, so a discounted VAT-inclusive rate still reconciles.",
                        max_digits=5,
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "offering",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="PROTECTed: an offering that has been sold cannot be deleted out from under the orders that reference it.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="catalogue.serviceoffering",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="samples.order",
                    ),
                ),
                (
                    "source_price",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Which published rate this line copied. Provenance only -- the snapshot above is what the line is billed at.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="catalogue.offeringprice",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical order item",
                "verbose_name_plural": "historical order items",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "unit_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The offering's published figure at the moment this line was created. Whether it includes VAT is stated by vat_treatment.",
                        max_digits=10,
                    ),
                ),
                ("currency", models.CharField(default="PHP", max_length=3)),
                (
                    "vat_treatment",
                    models.CharField(
                        choices=[
                            ("exclusive", "VAT-exclusive (net)"),
                            ("inclusive", "VAT-inclusive (gross)"),
                        ],
                        default="exclusive",
                        max_length=16,
                    ),
                ),
                (
                    "vat_rate_pct",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("12.00"), max_digits=5
                    ),
                ),
                (
                    "discount_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Applied to the line before VAT is split out, so a discounted VAT-inclusive rate still reconciles.",
                        max_digits=5,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "offering",
                    models.ForeignKey(
                        help_text="PROTECTed: an offering that has been sold cannot be deleted out from under the orders that reference it.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_items",
                        to="catalogue.serviceoffering",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="samples.order",
                    ),
                ),
                (
                    "source_price",
                    models.ForeignKey(
                        blank=True,
                        help_text="Which published rate this line copied. Provenance only -- the snapshot above is what the line is billed at.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="catalogue.offeringprice",
                    ),
                ),
            ],
            options={
                "db_table": "order_item",
                "ordering": ["id"],
            },
        ),
        migrations.AddConstraint(
            model_name="orderitem",
            constraint=models.CheckConstraint(
                check=models.Q(("quantity__gt", 0)), name="order_item_quantity_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="orderitem",
            constraint=models.CheckConstraint(
                check=models.Q(("unit_amount__gte", 0)),
                name="order_item_unit_amount_not_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="orderitem",
            constraint=models.CheckConstraint(
                check=models.Q(("discount_pct__gte", 0), ("discount_pct__lte", 100)),
                name="order_item_discount_within_range",
            ),
        ),
    ]
