# Generated by Django 5.0.6 on 2026-09-04 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("samples", "0005_order_item_row_level_security"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalorderitem",
            name="unit_amount",
            field=models.DecimalField(
                decimal_places=2,
                help_text="The figure as it stood when this line was created. Whether it includes VAT is stated by vat_treatment.",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="unit_amount",
            field=models.DecimalField(
                decimal_places=2,
                help_text="The figure as it stood when this line was created. Whether it includes VAT is stated by vat_treatment.",
                max_digits=10,
            ),
        ),
    ]
