# Generated by Django 5.0.6 on 2026-09-10 10:03

import django.db.models.deletion
import django.utils.timezone
import django_fsm
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("samples", "0006_alter_historicalorderitem_unit_amount_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SampleCodeSequence",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "prefix",
                    models.CharField(
                        help_text="Service-line prefix, e.g. 'WE'.", max_length=8
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        help_text="Allocation month as YYYYMM.", max_length=6
                    ),
                ),
                (
                    "last_number",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Highest number issued for this prefix/period.",
                    ),
                ),
            ],
            options={
                "db_table": "sample_code_sequence",
                "ordering": ["prefix", "period"],
            },
        ),
        migrations.CreateModel(
            name="SampleReceipt",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "received_at",
                    models.DateTimeField(
                        help_text="Arrival time as observed, mirrored onto Sample.received_at."
                    ),
                ),
                (
                    "received_from",
                    models.CharField(
                        blank=True,
                        help_text="Courier, sampler or customer representative who handed the item over.",
                        max_length=255,
                    ),
                ),
                (
                    "condition_on_receipt",
                    models.CharField(
                        choices=[
                            ("intact", "Intact"),
                            ("damaged", "Damaged"),
                            ("leaking", "Leaking"),
                            ("seal_broken", "Seal broken"),
                            ("temperature_excursion", "Temperature excursion"),
                            ("insufficient_quantity", "Insufficient quantity"),
                            ("other", "Other nonconformity"),
                        ],
                        default="intact",
                        max_length=32,
                    ),
                ),
                (
                    "receipt_temperature_c",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Measured temperature on arrival, where the method specifies one.",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "temperature_conforms",
                    models.BooleanField(
                        blank=True,
                        help_text="Null when no temperature requirement applies to this item -- not the same as conforming.",
                        null=True,
                    ),
                ),
                ("seal_intact", models.BooleanField(default=True)),
                ("volume_sufficient", models.BooleanField(default=True)),
                ("container_conforms", models.BooleanField(default=True)),
                ("preservation_conforms", models.BooleanField(default=True)),
                ("labelling_legible", models.BooleanField(default=True)),
                (
                    "storage_location",
                    models.CharField(
                        blank=True,
                        help_text="Where the item was put pending prep (7.4.4).",
                        max_length=255,
                    ),
                ),
                (
                    "deviations",
                    models.TextField(
                        blank=True,
                        help_text="Required whenever any check above fails -- enforced by a CHECK constraint, per 7.4.3.",
                    ),
                ),
                ("customer_consulted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "consultation_outcome",
                    models.TextField(
                        blank=True,
                        help_text="What the customer instructed. 7.4.3 requires the outcome be recorded, not just the call.",
                    ),
                ),
                (
                    "customer_authorised_despite_deviation",
                    models.BooleanField(
                        default=False,
                        help_text="The customer required testing to proceed knowing the deviation. Triggers the report disclaimer.",
                    ),
                ),
                ("report_disclaimer_required", models.BooleanField(default=False)),
                (
                    "disclaimer_text",
                    models.TextField(
                        blank=True,
                        help_text="Which results may be affected by the deviation. Printed on the COA when the flag above is set.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "sample_receipt",
                "ordering": ["-received_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="chainofcustodyevent",
            options={"ordering": ["sample_id", "occurred_at", "timestamp"]},
        ),
        migrations.AddField(
            model_name="chainofcustodyevent",
            name="occurred_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="When custody actually changed hands. Operator-supplied, defaults to now, never in the future.",
            ),
        ),
        migrations.AddField(
            model_name="historicalchainofcustodyevent",
            name="occurred_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="When custody actually changed hands. Operator-supplied, defaults to now, never in the future.",
            ),
        ),
        migrations.AddField(
            model_name="historicalsample",
            name="received_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Set by the receive transition from the operator-supplied arrival time. Null until the item arrives.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sample",
            name="received_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Set by the receive transition from the operator-supplied arrival time. Null until the item arrives.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="chainofcustodyevent",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="When this row was written. System clock, not the event time -- see occurred_at.",
            ),
        ),
        migrations.AlterField(
            model_name="historicalchainofcustodyevent",
            name="timestamp",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                help_text="When this row was written. System clock, not the event time -- see occurred_at.",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsample",
            name="status",
            field=django_fsm.FSMField(
                choices=[
                    ("pre_registered", "Pre-registered"),
                    ("registered", "Registered"),
                    ("received", "Received"),
                    ("receipt_rejected", "Rejected at Receipt"),
                    ("in_prep", "In Prep"),
                    ("in_testing", "In Testing"),
                    ("under_review", "Under Review"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("under_investigation", "Under Investigation"),
                    ("retest_pending", "Retest Pending"),
                    ("disposed", "Disposed"),
                ],
                default="pre_registered",
                max_length=32,
                protected=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalsample",
            name="unique_sample_code",
            field=models.CharField(
                db_index=True,
                help_text="Allocated server-side by apps.samples.identity.allocate_sample_code and immutable thereafter (ISO/IEC 17025:2017 7.4.2 -- the identification is retained for the life of the item). A trigger on this table, not just the serializer, refuses a change.",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="sample",
            name="status",
            field=django_fsm.FSMField(
                choices=[
                    ("pre_registered", "Pre-registered"),
                    ("registered", "Registered"),
                    ("received", "Received"),
                    ("receipt_rejected", "Rejected at Receipt"),
                    ("in_prep", "In Prep"),
                    ("in_testing", "In Testing"),
                    ("under_review", "Under Review"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("under_investigation", "Under Investigation"),
                    ("retest_pending", "Retest Pending"),
                    ("disposed", "Disposed"),
                ],
                default="pre_registered",
                max_length=32,
                protected=True,
            ),
        ),
        migrations.AlterField(
            model_name="sample",
            name="unique_sample_code",
            field=models.CharField(
                db_index=True,
                help_text="Allocated server-side by apps.samples.identity.allocate_sample_code and immutable thereafter (ISO/IEC 17025:2017 7.4.2 -- the identification is retained for the life of the item). A trigger on this table, not just the serializer, refuses a change.",
                max_length=64,
                unique=True,
            ),
        ),
        migrations.CreateModel(
            name="HistoricalSampleReceipt",
            fields=[
                ("id", models.BigIntegerField(blank=True, db_index=True)),
                (
                    "received_at",
                    models.DateTimeField(
                        help_text="Arrival time as observed, mirrored onto Sample.received_at."
                    ),
                ),
                (
                    "received_from",
                    models.CharField(
                        blank=True,
                        help_text="Courier, sampler or customer representative who handed the item over.",
                        max_length=255,
                    ),
                ),
                (
                    "condition_on_receipt",
                    models.CharField(
                        choices=[
                            ("intact", "Intact"),
                            ("damaged", "Damaged"),
                            ("leaking", "Leaking"),
                            ("seal_broken", "Seal broken"),
                            ("temperature_excursion", "Temperature excursion"),
                            ("insufficient_quantity", "Insufficient quantity"),
                            ("other", "Other nonconformity"),
                        ],
                        default="intact",
                        max_length=32,
                    ),
                ),
                (
                    "receipt_temperature_c",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Measured temperature on arrival, where the method specifies one.",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "temperature_conforms",
                    models.BooleanField(
                        blank=True,
                        help_text="Null when no temperature requirement applies to this item -- not the same as conforming.",
                        null=True,
                    ),
                ),
                ("seal_intact", models.BooleanField(default=True)),
                ("volume_sufficient", models.BooleanField(default=True)),
                ("container_conforms", models.BooleanField(default=True)),
                ("preservation_conforms", models.BooleanField(default=True)),
                ("labelling_legible", models.BooleanField(default=True)),
                (
                    "storage_location",
                    models.CharField(
                        blank=True,
                        help_text="Where the item was put pending prep (7.4.4).",
                        max_length=255,
                    ),
                ),
                (
                    "deviations",
                    models.TextField(
                        blank=True,
                        help_text="Required whenever any check above fails -- enforced by a CHECK constraint, per 7.4.3.",
                    ),
                ),
                ("customer_consulted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "consultation_outcome",
                    models.TextField(
                        blank=True,
                        help_text="What the customer instructed. 7.4.3 requires the outcome be recorded, not just the call.",
                    ),
                ),
                (
                    "customer_authorised_despite_deviation",
                    models.BooleanField(
                        default=False,
                        help_text="The customer required testing to proceed knowing the deviation. Triggers the report disclaimer.",
                    ),
                ),
                ("report_disclaimer_required", models.BooleanField(default=False)),
                (
                    "disclaimer_text",
                    models.TextField(
                        blank=True,
                        help_text="Which results may be affected by the deviation. Printed on the COA when the flag above is set.",
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "received_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="PROTECTed: the person who accepted an item cannot be deleted out from under the record saying so.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sample",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="samples.sample",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical sample receipt",
                "verbose_name_plural": "historical sample receipts",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddConstraint(
            model_name="samplecodesequence",
            constraint=models.UniqueConstraint(
                fields=("prefix", "period"), name="sample_code_sequence_unique_period"
            ),
        ),
        migrations.AddField(
            model_name="samplereceipt",
            name="received_by",
            field=models.ForeignKey(
                help_text="PROTECTed: the person who accepted an item cannot be deleted out from under the record saying so.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sample_receipts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="samplereceipt",
            name="sample",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="receipt",
                to="samples.sample",
            ),
        ),
        migrations.AddIndex(
            model_name="samplereceipt",
            index=models.Index(
                fields=["report_disclaimer_required"],
                name="sample_rece_report__6fbce4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="samplereceipt",
            index=models.Index(
                fields=["received_at"], name="sample_rece_receive_eb626d_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="samplereceipt",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("condition_on_receipt", "intact"),
                        ("seal_intact", True),
                        ("volume_sufficient", True),
                        ("container_conforms", True),
                        ("preservation_conforms", True),
                        ("labelling_legible", True),
                        models.Q(
                            ("temperature_conforms", True),
                            ("temperature_conforms__isnull", True),
                            _connector="OR",
                        ),
                    ),
                    models.Q(("deviations", ""), _negated=True),
                    _connector="OR",
                ),
                name="sample_receipt_deviation_recorded",
            ),
        ),
        migrations.AddConstraint(
            model_name="samplereceipt",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("customer_authorised_despite_deviation", False),
                    models.Q(("consultation_outcome", ""), _negated=True),
                    _connector="OR",
                ),
                name="sample_receipt_authorisation_needs_consultation",
            ),
        ),
        migrations.AddConstraint(
            model_name="samplereceipt",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("report_disclaimer_required", False),
                    models.Q(("disclaimer_text", ""), _negated=True),
                    _connector="OR",
                ),
                name="sample_receipt_disclaimer_has_text",
            ),
        ),
    ]
