# Generated by Django 5.0.6 on 2026-09-10 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("samples", "0010_sample_receipt_row_level_security"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalsample",
            name="priority",
            field=models.CharField(
                choices=[
                    ("routine", "Routine"),
                    ("rush", "Rush"),
                    ("emergency", "Emergency"),
                ],
                default="routine",
                help_text="Commercial turnaround priority. Not a holding time -- see TestRequest.due_at.",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="sample",
            name="priority",
            field=models.CharField(
                choices=[
                    ("routine", "Routine"),
                    ("rush", "Rush"),
                    ("emergency", "Emergency"),
                ],
                default="routine",
                help_text="Commercial turnaround priority. Not a holding time -- see TestRequest.due_at.",
                max_length=16,
            ),
        ),
        migrations.AddIndex(
            model_name="sample",
            index=models.Index(fields=["priority"], name="sample_priorit_c66f4d_idx"),
        ),
    ]
