# Generated by Django 5.0.6 on 2026-09-28 10:50

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("samples", "0011_holding_time_deadlines"),
        ("testing", "0004_backfill_holding_time_deadlines"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalLabelPrintEvent",
            fields=[
                ("id", models.BigIntegerField(blank=True, db_index=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("container", "Container label"),
                            ("worksheet", "Worksheet / aliquot label"),
                            ("job_order", "Job order sheet"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "copies",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Pages printed. For container labels this is the container count.",
                    ),
                ),
                ("printed_at", models.DateTimeField(blank=True, editable=False)),
                (
                    "is_reprint",
                    models.BooleanField(
                        default=False,
                        help_text="Derived: an earlier print of this kind already exists for this target. Never client-supplied.",
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True,
                        help_text="Why a label was printed again. Required on a reprint -- enforced by a CHECK constraint.",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="samples.order",
                    ),
                ),
                (
                    "printed_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="PROTECTed: the person who put an identity on a container cannot be deleted out from under the record.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sample",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="samples.sample",
                    ),
                ),
                (
                    "test_request",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Set for worksheet labels, which identify a portion taken for one analysis.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="testing.testrequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical label print event",
                "verbose_name_plural": "historical label print events",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="LabelPrintEvent",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("container", "Container label"),
                            ("worksheet", "Worksheet / aliquot label"),
                            ("job_order", "Job order sheet"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "copies",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Pages printed. For container labels this is the container count.",
                    ),
                ),
                ("printed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_reprint",
                    models.BooleanField(
                        default=False,
                        help_text="Derived: an earlier print of this kind already exists for this target. Never client-supplied.",
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True,
                        help_text="Why a label was printed again. Required on a reprint -- enforced by a CHECK constraint.",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="label_print_events",
                        to="samples.order",
                    ),
                ),
                (
                    "printed_by",
                    models.ForeignKey(
                        help_text="PROTECTed: the person who put an identity on a container cannot be deleted out from under the record.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="label_print_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sample",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="label_print_events",
                        to="samples.sample",
                    ),
                ),
                (
                    "test_request",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set for worksheet labels, which identify a portion taken for one analysis.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="label_print_events",
                        to="testing.testrequest",
                    ),
                ),
            ],
            options={
                "db_table": "label_print_event",
                "ordering": ["-printed_at"],
                "indexes": [
                    models.Index(
                        fields=["sample", "kind"], name="label_print_sample__49002f_idx"
                    ),
                    models.Index(
                        fields=["printed_at"], name="label_print_printed_e215b4_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="labelprintevent",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("sample__isnull", False),
                    ("order__isnull", False),
                    ("test_request__isnull", False),
                    _connector="OR",
                ),
                name="label_print_event_target_required",
            ),
        ),
        migrations.AddConstraint(
            model_name="labelprintevent",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("is_reprint", False),
                    models.Q(("reason", ""), _negated=True),
                    _connector="OR",
                ),
                name="label_print_event_reprint_has_reason",
            ),
        ),
        migrations.AddConstraint(
            model_name="labelprintevent",
            constraint=models.CheckConstraint(
                check=models.Q(("copies__gt", 0)),
                name="label_print_event_copies_positive",
            ),
        ),
    ]
